### ISSUE TITLE
Testing controller which are using node modules

### ISSUE THREAD

**Issue by MiLk** [intelligentgolf/karma-nodewebkit-launcher#15]
I'm currently working on an application using node-webkit and AngularJS.

I tried to use the `karma-nodewebkit-launcher` module,
as I didn't find any other solution to run tests on the AngularJS part.

But I have an issue.
When I add a controller which use a node module to the file list in `karma.conf.js`,
I obtain the following error:
```
  Uncaught RangeError: Maximum call stack size exceeded
  at http://localhost:9876/context.html:1
```

I'm using node-webkit 0.8.4 with OSX 10.8.5.

My `karma.conf.js` is:
```
module.exports = function(config) {
  config.set({
    basePath: '../',

    files: [
      'app/assets/js/jquery/jquery.min.js',
      'app/assets/js/jquery/jquery-ui.min.js',
      'app/assets/js/angular/angular.min.js',
      'app/assets/js/angular/angular-route.min.js',
      'app/assets/js/angular/angular-mocks.js',
      //'app/assets/js/files/bootstrap.js',
      //'app/assets/js/files/functions.js',
      //'app/lib/**/*.js',
      'app/scripts/app.js',
      'app/scripts/controllers/*.js',
      'test/spec/controllers/*.js',
      'app/scripts/directives/*.js',
      'test/spec/directives/*.js'
    ],

    exclude: [
      'app/assets/js/jquery/plugins/uploader/*.js',
    ],

    autoWatch: false,

    frameworks: ['mocha'],

    browsers: ['NodeWebkit'],

    singleRun: true
  });
};
```

Did I do something wrong ?
Is there a file missing in my `karma.conf.js` ?

Thank you.

**Comment by michalc** [comment]
@boneskull The mocha build appears to have now been merged.

@MiLk I've included your suggestion, thanks. If there appears to be no problems, I'll bump the version in npm.

**Comment by michalc** [comment]
Version bumped, closing this issue. If there are problems with the new version, feel free to post again.
