### ISSUE TITLE
Loading a file with 'require' fails

### ISSUE THREAD

**Issue by vasanthps** [intelligentgolf/karma-nodewebkit-launcher#25]
Loading a file that contains a require fails with the error <B>Uncaught RangeError: Maximum call stack size exceeded</B>

**Comment by michalc** [comment]
Hi @vasanthps,

Can you post a few more details, enough to reproduce the issue? At least your karma configuration, path structure of where your source files are, where the module you're trying to load is, specifically how you're using `require`, and anything else that you think might be helpful.

Thanks,

Michal.

**Comment by michalc** [comment]
Closing this due to lack of response. Feel free to comment with more information to reopen.
