### ISSUE TITLE
Hide GUI

### ISSUE THREAD

**Issue by monolithed** [intelligentgolf/karma-nodewebkit-launcher#33]
I'd like to run the tests without any GUI like PhantomJS.
Is there any way to implement the invisible mode?
 
![1428098513254](https://cloud.githubusercontent.com/assets/803674/6989646/d127e7d4-da66-11e4-9ea1-cf69c1198cae.png)

**Comment by michalc** [comment]
Does NodeWebkit / NW.js have an invisible mode? I can't see one at https://github.com/nwjs/nw.js/wiki/Manifest-format . If no, then I suspect this won't be possible.

**Comment by monolithed** [comment]
@michalc, got it, thanks
