### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by julmot** [intelligentgolf/karma-nodewebkit-launcher#35]
I see a great need for such plugin. Is it still maintained? First I think it should be renamed to karma-nw.js-launcher to make sure it'll be found.

**Comment by julmot** [comment]
Ping @dignifiedquire since you're in the list of [maintainers](https://github.com/intelligentgolf/karma-nodewebkit-launcher/blob/master/package.json#L44)

**Comment by dignifiedquire** [comment]
@julmot not by me currently sorry

**Comment by julmot** [comment]
@dignifiedquire Thanks. In that case ping @michalc!?

**Comment by julmot** [comment]
I see this as a no :-(

**Comment by michalc** [comment]
@julmot I haven't been maintaining it, but happy to get back on the horse!
