### ISSUE TITLE
Update nw dependency

### ISSUE THREAD

**Issue by julmot** [intelligentgolf/karma-nodewebkit-launcher#36]
And allow specyfing custom nw versions, e.g. to affect the `toolbar` option that has been removed in 0.13.

**Comment by michalc** [comment]
@julmot Updating the version seems good. I can do this (or if you can submit a PR?)

However, I'm not sure of a good way of customising the nw version. Do you have any suggestions?

**Comment by michalc** [comment]
@julmot I have updated to the latest nw, and published a new version of karma-nodewebkit-launcher to npm. 

https://github.com/intelligentgolf/karma-nodewebkit-launcher/pull/37 and
https://github.com/intelligentgolf/karma-nodewebkit-launcher/pull/38

For reference, users who still want the old version can pin their package.json to the old version.

Closing this issue. For the customising of nw version (which I'm not 100% sure on the best way to do...), feel free to open another issue.
